LET SCREEN_WIDTH = 80
LET SCREEN_HEIGHT = 22
LET BUFFER_SIZE = SCREEN_WIDTH * SCREEN_HEIGHT
DIM LUMINANCE_CHARS(12)
LUMINANCE_CHARS(0) = 46
LUMINANCE_CHARS(1) = 44
LUMINANCE_CHARS(2) = 45
LUMINANCE_CHARS(3) = 126
LUMINANCE_CHARS(4) = 58
LUMINANCE_CHARS(5) = 59
LUMINANCE_CHARS(6) = 61
LUMINANCE_CHARS(7) = 33
LUMINANCE_CHARS(8) = 42
LUMINANCE_CHARS(9) = 35
LUMINANCE_CHARS(10) = 36
LUMINANCE_CHARS(11) = 64
LET ROTATION_A = 0.0
LET ROTATION_B = 0.0

DIM DEPTH_BUFFER(BUFFER_SIZE)
DIM SCREEN_BUFFER(BUFFER_SIZE)


1 FOR I = 0 TO BUFFER_SIZE-1
    SCREEN_BUFFER(I) = 32
NEXT I

FOR I = 0 TO BUFFER_SIZE-1
    DEPTH_BUFFER(I) = 0
NEXT I

LET SIN_A = SINF(ROTATION_A)
LET COS_A = COSF(ROTATION_A)
LET SIN_B = SINF(ROTATION_B)
LET COS_B = COSF(ROTATION_B)

FOR I = 0 TO 89
    LET X = 0.07*I
    LET SIN_I = SINF(X)
    LET COS_I = COSF(X)
    FOR J = 0 TO 313
        LET Y = 0.02*J
        LET SIN_J = SINF(Y)
        LET COS_J = COSF(Y)
        LET CIRCLE_RADIUS = COS_J + 2.0
        LET INVERSE_DEPTH = 1.0 / (SIN_I * CIRCLE_RADIUS * SIN_A + SIN_J * COS_A + 5.0)
        LET TRANSFORMED_Y = SIN_I * CIRCLE_RADIUS * COS_A - SIN_J * SIN_A
        LET SCREEN_X = 40 + INT(30.0 * INVERSE_DEPTH * (COS_I * CIRCLE_RADIUS * COS_B - TRANSFORMED_Y * SIN_B))
        LET SCREEN_Y = 12 + INT(15.0 * INVERSE_DEPTH * (COS_I * CIRCLE_RADIUS * SIN_B + TRANSFORMED_Y * COS_B))
        LET BUFFER_INDEX = SCREEN_X + SCREEN_WIDTH * SCREEN_Y
        IF BUFFER_INDEX < 0
            BUFFER_INDEX = 0
        FI
        IF BUFFER_INDEX >= BUFFER_SIZE
            BUFFER_INDEX = BUFFER_SIZE-1
        FI
        LET LUMINANCE = INT(8.0 * ((SIN_J * SIN_A - SIN_I * COS_J * COS_A) * COS_B - SIN_I * COS_J * SIN_A - SIN_J * COS_A - COS_I * COS_J * SIN_B))

        IF (SCREEN_Y > 0 AND SCREEN_Y < SCREEN_HEIGHT AND SCREEN_X > 0 AND SCREEN_X < SCREEN_WIDTH AND INVERSE_DEPTH > DEPTH_BUFFER(BUFFER_INDEX))
            depth_buffer(BUFFER_INDEX) = INVERSE_DEPTH
            IF LUMINANCE < 0
                LUMINANCE = 0
            FI
            IF LUMINANCE > 11
                LUMINANCE = 11
            FI
            SCREEN_BUFFER(BUFFER_INDEX) = LUMINANCE_CHARS(LUMINANCE)
        FI


    NEXT J
NEXT I

HOME

FOR I = 0 TO BUFFER_SIZE
    IF I % SCREEN_WIDTH = 0
        PUTCHAR 10
    ELSE
        PUTCHAR SCREEN_BUFFER(I)
    FI
NEXT I

ROTATION_A = ROTATION_A + 0.04
ROTATION_B = ROTATION_B + 0.02


GOTO 1
